[unix_http_server]
file=/root/rednote-spider/logs/supervisor.sock
chmod=0700

[supervisord]
user=root
logfile=/root/rednote-spider/logs/supervisord.log
pidfile=/root/rednote-spider/logs/supervisord.pid
childlogdir=/root/rednote-spider/logs
loglevel=info
nodaemon=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///root/rednote-spider/logs/supervisor.sock

[include]
files = /root/rednote-spider/deploy/supervisor/runtime/*.conf
